# Generated by Django 4.2.5 on 2024-02-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='Genero')),
                ('lugar_nacimiento', models.CharField(max_length=45, verbose_name='Lugar de Nacimiento')),
                ('fecha_nacimiento', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha de Nacimiento')),
                ('edad', models.IntegerField(verbose_name='Edad deportista')),
                ('peso', models.FloatField(max_length=5, verbose_name='Peso en Kg')),
                ('estatura', models.FloatField(max_length=5, verbose_name='Estatura en Cm')),
                ('ciudad', models.CharField(max_length=45, verbose_name='Ciudad de Residencia')),
                ('barrio', models.CharField(max_length=45, verbose_name='Barrio')),
                ('direccion', models.CharField(max_length=45, verbose_name='Direccion')),
                ('eps', models.CharField(max_length=45, verbose_name='EPS')),
                ('anexo', models.CharField(max_length=10, verbose_name='Anexo Documento')),
            ],
        ),
    ]
