# Generated by Django 4.2.5 on 2024-03-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.TextField(max_length=45, verbose_name='Genero')),
                ('lugarNacimiento', models.TextField(max_length=45, verbose_name='Lugar de Nacimiento')),
                ('fechaNacimiento', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha de Nacimiento')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('peso', models.IntegerField(verbose_name='Peso en Kg')),
                ('estatura', models.IntegerField(verbose_name='Estatura')),
                ('ciudad', models.TextField(max_length=45, verbose_name='Ciudad')),
                ('barrio', models.TextField(max_length=45, verbose_name='Barrio')),
                ('direccion', models.TextField(max_length=45, verbose_name='Direccion')),
                ('eps', models.TextField(max_length=45, verbose_name='Eps')),
                ('estado', models.CharField(choices=[('1', 'SI'), ('0', 'NO')], default='1', max_length=2, verbose_name='Estado Activo?')),
            ],
        ),
    ]
