# Generated by Django 4.2.5 on 2024-02-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=255, verbose_name='Mes Pago')),
                ('imagen', models.ImageField(upload_to='imagen_pagos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='deportista',
            name='anexo',
        ),
    ]
