# Generated by Django 4.2.5 on 2024-03-25 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deportista', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deportista',
            old_name='fechaNacimiento',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='deportista',
            old_name='lugarNacimiento',
            new_name='lugar_nacimiento',
        ),
    ]
