# Generated by Django 4.2.5 on 2024-02-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportista', '0002_imagen_remove_deportista_anexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=255)),
                ('reporte_pago', models.ImageField(upload_to='imagenes/')),
            ],
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
