# Generated by Django 4.2.5 on 2024-02-14 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deportista', '0003_reporte_pago_delete_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deportista',
            old_name='eps',
            new_name='epi',
        ),
        migrations.RenameField(
            model_name='reporte_pago',
            old_name='mes',
            new_name='mes_pago',
        ),
    ]
